# Generated by Django 4.2 on 2024-07-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nome')),
                ('document', models.TextField(max_length=11, verbose_name='CPF')),
                ('email', models.TextField(max_length=30, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Procedimento',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nome')),
                ('document', models.TextField(max_length=11, verbose_name='CPF')),
                ('email', models.TextField(max_length=30, verbose_name='E-mail')),
                ('specialty', models.TextField(max_length=30, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Profissional',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nome da Sala')),
            ],
            options={
                'verbose_name': 'Sala',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('DONE', 'Done'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=10)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pacient')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professional')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'Agendamento',
            },
        ),
    ]
